- name: Create stack user
  user: name=stack comment="Director Installation User" shell=/bin/bash

- name: Ensure that .ssh directory exist in stack user home
  file: path=/home/stack/.ssh state=directory owner=stack group=stack mode=0700

- name: Deploy ssh key for the stack user
  copy: src=~/.ssh/id_rsa.pub dest=/home/stack/.ssh/authorized_keys owner=stack group=stack mode=0600

- name: Set sudo permissions for stack user
  lineinfile: dest=/etc/sudoers.d/stack line="stack ALL=(root) NOPASSWD:ALL" state=present create=yes mode=0440 owner=root group=root

